name: Test clear github cache

on:
  pull_request:
    types: [closed]

jobs:
  cleanup-caches:
    name: Use reusable clear github cache workflow
    uses: philipseo/actions/.github/workflows/reusable-clear-github-cache.yml@main
    with:
      github-token: ${{ secrets.GH_TOKEN }}
