name: Test Cleanup caches by a branch

on:
  pull_request:
    types: [opened, synchronize, closed]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cleanup-caches:
    uses: philipseo/actions/.github/workflows/cleanup-caches.yml@main
    with:
      github-token: ${{ secrets.GH_TOKEN }}
