name: Test Cleanup caches by a branch

on:
  pull_request:
    types: [opened, closed]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cleanup-caches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: cleanup caches
        uses: philipseo/actions/workflows/cleanup-caches.yml@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
