name: Test Lint

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    name: Use Reusable Lint Workflow
    uses: philipseo/actions/.github/workflows/reusable-lint.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
