name: Test versioning

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    name: Use Reusable Lint Workflow
    uses: philipseo/actions/.github/workflows/reusable-versioning.yml@main
    with:
      github-token: ${{ secrets.GH_TOKEN }}
